### PR TITLE
Initial revision

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by itajaja** [comment]
I'd add import statement rules. Too bad that most of these can't be automated

**Comment by taion** [comment]
Those are right out of PEP 8 for us though.

**Comment by cancan101** [comment]
https://github.com/PyCQA/flake8-import-order

**Comment by taion** [comment]
I'd love to set up more detailed linting for Python, but let's codify what we're doing right now w/r/t written guidelines first.

This isn't like on the JS side, where we already had a very, very good linting tool and just wanted to centralize our overrides. Unfortunately for all of us, Python tooling is a flaming dumpster fire.

**Pull request merged**
